import React, { createContext, useState, useEffect } from 'react'

export const ThemeContext = createContext(null)

// Pixel values behind each Font Size option in Settings.
// All font-size rules in App.css are written in rem, so changing the
// root (html) font-size scales every page's text together.
export const fontSizeValues = {
  small: 14,
  medium: 16,
  large: 18
}

// Translation dictionary for navigation labels and common buttons.
export const translations = {
  en: {
    dashboard: 'Dashboard',
    customers: 'Customers',
    designers: 'Designers',
    contractors: 'Contractors',
    suppliers: 'Suppliers',
    projects: 'Projects',
    materials: 'Materials',
    appointments: 'Appointments',
    quotations: 'Quotations',
    payments: 'Payments',
    reports: 'Reports',
    settings: 'Settings',
    addCustomer: 'Add Customer',
    searchPlaceholder: 'Search customers, projects...',
    searchCustomers: 'Search by customer name or project...',
    customerDirectory: 'Customer Directory',
    allCustomers: 'All Customers',
    active: 'Active',
    inactive: 'Inactive',
    newCustomers: 'New Customers',
    viewDetails: 'View Details',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    totalCustomers: 'Total Customers',
    activeCustomers: 'Active Customers',
    newThisMonth: 'New This Month',
    completedProjects: 'Completed Projects',
    pageTitle: 'Customers',
    pageSubtitle: "Manage your clients and their interior design projects.",
    notifications: 'Notifications',
    messages: 'Messages',
    administratorRole: 'Administrator',
    selectLanguage: 'Select language',
    toggleToDark: 'Switch to dark theme',
    toggleToLight: 'Switch to light theme',
    pendingQuotations: 'Pending Quotations',
    customerNameLabel: 'Customer Name',
    phoneLabel: 'Phone',
    emailLabel: 'Email',
    locationLabel: 'Location',
    projectTypeLabel: 'Project Type',
    assignedDesignerLabel: 'Assigned Designer',
    statusLabel: 'Status',
    completed: 'Completed',
    nameRequired: 'Customer name is required.',
    emptyState: 'No customers found.',
    clearSearch: 'Clear search',
    resetForm: 'Reset',
    closeModal: 'Close',
    welcomeBackPrefix: 'Welcome back',
    dashboardSubtitle: "Here's what's happening with your interior design projects today.",
    activeProjects: 'Active Projects',
    recentProjects: 'Recent Projects',
    recentCustomers: 'Recent Customers',
    viewAll: 'View All',
    projectsPageTitle: 'Project Management',
    projectsPageSubtitle: 'Track interior design projects, progress, budgets and timelines.',
    allProjects: 'All Projects',
    ongoing: 'Ongoing',
    onHold: 'On Hold',
    customerLabel: 'Customer',
    designerLabel: 'Designer',
    startDateLabel: 'Start Date',
    endDateLabel: 'End Date',
    settingsPageTitle: 'Settings',
    settingsPageSubtitle: 'Personalize how the IDCP portal looks and feels.',
    appearanceSection: 'Appearance',
    appearanceDesc: 'Choose how the IDCP Portal looks to you.',
    fontSizeSection: 'Font Size',
    fontSizeDesc: 'Adjust the text size across the entire application.',
    languageSection: 'Language',
    languageDesc: 'Choose your preferred display language.',
    themeSection: 'Theme / Background',
    themeDesc: 'Switch between the light and dark portal theme.',
    small: 'Small',
    medium: 'Medium',
    large: 'Large',
    lightTheme: 'Light Theme',
    darkTheme: 'Dark Theme',
    materialsPageSubtitle: 'Manage interior materials, stock levels, suppliers and availability.',
    quotationsPageSubtitle: 'Create, manage and track project quotations and customer approvals.',
    designersPageSubtitle: 'Your in-house design team and their active workload.',
    contractorsPageSubtitle: 'Trusted contractors working across your ongoing projects.',
    categoryLabel: 'Category',
    supplierLabel: 'Supplier',
    priceLabel: 'Price',
    stockLabel: 'Stock',
    inStock: 'In Stock',
    lowStock: 'Low Stock',
    outOfStock: 'Out of Stock',
    specializationLabel: 'Specialization',
    experienceLabel: 'Experience',
    activeProjectsLabel: 'Active Projects',
    amountLabel: 'Amount',
    dateLabel: 'Date',
    pending: 'Pending',
    approved: 'Approved',
    rejected: 'Rejected',
    contractorTypeLabel: 'Trade',
    comingSoonTitle: 'Coming Soon',
    comingSoonDesc: 'This module is under development and will be available in a future update.',
    notFoundTitle: 'Page Not Found',
    notFoundDesc: "The page you're looking for doesn't exist or has been moved.",
    backToDashboard: 'Back to Dashboard',
    loginWelcomeTitle: 'Welcome Back',
    loginSubtitle: 'Sign in to continue managing your interior design projects.',
    passwordLabel: 'Password',
    rememberMe: 'Remember Me',
    forgotPassword: 'Forgot Password?',
    loginButton: 'Login',
    orDivider: 'OR',
    continueWithGoogle: 'Continue with Google',
    loginFooter: '© 2026 IDCP Portal',
    invalidCredentials: 'Invalid email or password.',
    portalTagline: 'Design • Coordinate • Deliver',
    heroTitleLine1: 'Interior Designer',
    heroTitleLine2: 'Coordination Portal',
    heroFeature1: 'Manage Interior Projects',
    heroFeature2: 'Track Materials & Quotations',
    heroFeature3: 'Coordinate Designers & Contractors',
    craftingTagline: 'Crafting premium interior experiences.',
    logout: 'Logout',
    demoCredentialsLabel: 'Demo credentials',
    loginAsLabel: 'Login as',
    roleDesignerLabel: 'Designer',
    roleContractorLabel: 'Contractor',
    roleCustomerLabel: 'Customer',
    wrongRoleTab: 'These credentials belong to a different role tab.',

    // ---- Project workflow / stage-based progress ----
    createProject: 'Create Project',
    currentStageLabel: 'Current Stage',
    nextStageLabel: 'Next Stage',
    overallProgressLabel: 'Overall Progress',
    viewProject: 'View Project',
    advanceStage: 'Advance Stage',
    projectCompleted: 'Project Completed',
    contractorLabel: 'Contractor',
    budgetLabel: 'Budget',
    timelineLabel: 'Timeline',
    stageTimelineLabel: 'Stage Timeline',
    workflowLabel: 'Project Workflow',
    quotationLabel: 'Quotation',
    paymentLabel: 'Payment',
    delayed: 'Delayed',

    // ---- Materials ----
    addMaterial: 'Add Material',
    newArrivals: 'New Arrivals',
    totalMaterials: 'Total Materials',
    materialInventory: 'Material Inventory',
    searchMaterials: 'Search materials by name, category or supplier...',
    materialNameLabel: 'Material Name',
    unitPriceLabel: 'Unit Price',
    quantityLabel: 'Quantity Available',

    // ---- Quotations ----
    createQuotation: 'Create Quotation',
    totalQuotations: 'Total Quotations',
    quotationDateLabel: 'Date',
    validUntilLabel: 'Valid Until',
    estimatedCostLabel: 'Estimated Cost',
    downloadPdf: 'Download PDF',

    // ---- Designers / Contractors ----
    totalDesigners: 'Total Designers',
    availableDesigners: 'Available Designers',
    busyDesigners: 'Busy Designers',
    totalContractors: 'Total Contractors',
    activeContractors: 'Active Contractors',
    ongoingWorks: 'Ongoing Works',
    completedWorks: 'Completed Works',
    employeeIdLabel: 'Employee ID',
    viewProfile: 'View Profile',
    available: 'Available',
    busy: 'Busy',
    ratingLabel: 'Rating',

    // ---- Suppliers ----
    suppliersPageTitle: 'Supplier Management',
    suppliersPageSubtitle: 'Manage material suppliers, product categories and delivery coordination.',
    addSupplier: 'Add Supplier',
    totalSuppliers: 'Total Suppliers',
    activeSuppliers: 'Active Suppliers',
    pendingDeliveries: 'Pending Deliveries',
    completedDeliveries: 'Completed Deliveries',
    supplierDirectory: 'Supplier Directory',
    searchSuppliers: 'Search suppliers, materials or categories...',
    materialsSuppliedLabel: 'Materials Supplied',
    contactPersonLabel: 'Contact Person',

    // ---- Appointments ----
    appointmentsPageTitle: 'Appointment Management',
    appointmentsPageSubtitle: 'Schedule and coordinate meetings between customers, designers and project teams.',
    scheduleAppointment: 'Schedule Appointment',
    todaysAppointments: "Today's Appointments",
    upcoming: 'Upcoming',
    cancelled: 'Cancelled',
    appointmentSchedule: 'Appointment Schedule',
    searchAppointments: 'Search customer, project or designer...',
    confirmed: 'Confirmed',

    // ---- Payments ----
    paymentsPageTitle: 'Payment Management',
    paymentsPageSubtitle: 'Track project payments, invoices, revenue and outstanding balances.',
    recordPayment: 'Record Payment',
    totalRevenue: 'Total Revenue',
    pendingPayments: 'Pending Payments',
    paidLabel: 'Paid',
    overdueLabel: 'Overdue',
    revenueTrend: 'Revenue Trend',
    revenueTrendSubtitle: 'Monthly collected revenue',
    paymentBreakdown: 'Payment Breakdown',
    totalInvoiced: 'Total Invoiced',
    paymentTransactions: 'Payment Transactions',
    searchPayments: 'Search invoice number, customer or project...',
    invoiceLabel: 'Invoice',
    methodLabel: 'Method',
    paymentDateLabel: 'Payment Date',

    // ---- Reports ----
    reportsPageTitle: 'Reports & Analytics',
    reportsPageSubtitle: 'Analyze projects, revenue, customers, materials and team performance.',
    exportReport: 'Export Report',
    revenueOverview: 'Revenue Overview',
    materialUsage: 'Material Usage',
    projectStatusDistribution: 'Project Status',
    customerGrowth: 'Customer Growth',
    designerPerformance: 'Designer Performance',
    thisMonth: 'This Month',

    // ---- Extended customer fields ----
    addressLabel: 'Address',
    propertyTypeLabel: 'Property Type',
    budgetRupeesLabel: 'Budget (₹)',
    requirementsLabel: 'Requirements',
    myProjectLabel: 'My Project'
  },
  ta: {
    dashboard: 'டாஷ்போர்டு',
    customers: 'வாடிக்கையாளர்கள்',
    designers: 'வடிவமைப்பாளர்கள்',
    contractors: 'ஒப்பந்தக்காரர்கள்',
    suppliers: 'சப்ளையர்கள்',
    projects: 'திட்டங்கள்',
    materials: 'பொருட்கள்',
    appointments: 'சந்திப்புகள்',
    quotations: 'மேற்கோள்கள்',
    payments: 'கொடுப்பனவுகள்',
    reports: 'அறிக்கைகள்',
    settings: 'அமைப்புகள்',
    addCustomer: 'வாடிக்கையாளரைச் சேர்',
    searchPlaceholder: 'வாடிக்கையாளர்கள், திட்டங்களைத் தேடு...',
    searchCustomers: 'பெயர் அல்லது திட்டத்தால் தேடு...',
    customerDirectory: 'வாடிக்கையாளர் அடைவு',
    allCustomers: 'அனைத்து வாடிக்கையாளர்கள்',
    active: 'செயலில்',
    inactive: 'செயலற்ற',
    newCustomers: 'புதிய வாடிக்கையாளர்கள்',
    viewDetails: 'விவரங்களைக் காண்க',
    delete: 'நீக்கு',
    save: 'சேமி',
    cancel: 'ரத்து செய்',
    totalCustomers: 'மொத்த வாடிக்கையாளர்கள்',
    activeCustomers: 'செயலில் உள்ள வாடிக்கையாளர்கள்',
    newThisMonth: 'இந்த மாதம் புதியது',
    completedProjects: 'முடிக்கப்பட்ட திட்டங்கள்',
    pageTitle: 'வாடிக்கையாளர்கள்',
    pageSubtitle: 'உங்கள் வாடிக்கையாளர்களையும் அவர்களின் உள்துறை வடிவமைப்பு திட்டங்களையும் நிர்வகிக்கவும்.',
    notifications: 'அறிவிப்புகள்',
    messages: 'செய்திகள்',
    administratorRole: 'நிர்வாகி',
    selectLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    toggleToDark: 'இருண்ட தீமுக்கு மாறு',
    toggleToLight: 'ஒளி தீமுக்கு மாறு',
    pendingQuotations: 'நிலுவையிலுள்ள மேற்கோள்கள்',
    customerNameLabel: 'வாடிக்கையாளர் பெயர்',
    phoneLabel: 'தொலைபேசி',
    emailLabel: 'மின்னஞ்சல்',
    locationLabel: 'இடம்',
    projectTypeLabel: 'திட்ட வகை',
    assignedDesignerLabel: 'நியமிக்கப்பட்ட வடிவமைப்பாளர்',
    statusLabel: 'நிலை',
    completed: 'முடிந்தது',
    nameRequired: 'வாடிக்கையாளர் பெயர் தேவை.',
    emptyState: 'வாடிக்கையாளர்கள் யாரும் இல்லை.',
    clearSearch: 'தேடலை அழி',
    resetForm: 'மீட்டமை',
    closeModal: 'மூடு',
    welcomeBackPrefix: 'மீண்டும் வரவேற்கிறோம்',
    dashboardSubtitle: 'இன்று உங்கள் உள்துறை வடிவமைப்பு திட்டங்களில் என்ன நடக்கிறது என்பதை இங்கே காணலாம்.',
    activeProjects: 'செயலில் உள்ள திட்டங்கள்',
    recentProjects: 'சமீபத்திய திட்டங்கள்',
    recentCustomers: 'சமீபத்திய வாடிக்கையாளர்கள்',
    viewAll: 'அனைத்தையும் காண்க',
    projectsPageTitle: 'திட்டங்கள்',
    projectsPageSubtitle: 'ஒவ்வொரு உள்துறை வடிவமைப்பு திட்டத்தையும் தொடக்கம் முதல் ஒப்படைப்பு வரை கண்காணிக்கவும்.',
    allProjects: 'அனைத்து திட்டங்கள்',
    ongoing: 'நடைபெறுகிறது',
    onHold: 'இடைநிறுத்தப்பட்டது',
    customerLabel: 'வாடிக்கையாளர்',
    designerLabel: 'வடிவமைப்பாளர்',
    startDateLabel: 'தொடக்க தேதி',
    endDateLabel: 'முடிவு தேதி',
    settingsPageTitle: 'அமைப்புகள்',
    settingsPageSubtitle: 'IDCP போர்ட்டல் எப்படி தெரிகிறது என்பதை தனிப்பயனாக்கவும்.',
    appearanceSection: 'தோற்றம்',
    appearanceDesc: 'IDCP போர்ட்டல் உங்களுக்கு எப்படி தெரிகிறது என்பதைத் தேர்ந்தெடுக்கவும்.',
    fontSizeSection: 'எழுத்துரு அளவு',
    fontSizeDesc: 'முழு பயன்பாட்டிலும் உரை அளவை சரிசெய்யவும்.',
    languageSection: 'மொழி',
    languageDesc: 'உங்களுக்கு விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்.',
    themeSection: 'தீம் / பின்னணி',
    themeDesc: 'ஒளி மற்றும் இருண்ட தீம் இடையே மாறவும்.',
    small: 'சிறியது',
    medium: 'நடுத்தரம்',
    large: 'பெரியது',
    lightTheme: 'ஒளி தீம்',
    darkTheme: 'இருண்ட தீம்',
    materialsPageSubtitle: 'ஒவ்வொரு திட்டத்திற்கான பொருட்கள் இருப்பு, சப்ளையர்கள் மற்றும் விலையைக் கண்காணிக்கவும்.',
    quotationsPageSubtitle: 'உங்கள் வாடிக்கையாளர்களுக்கு அனுப்பப்பட்ட மேற்கோள்களை மதிப்பாய்வு செய்யவும்.',
    designersPageSubtitle: 'உங்கள் உள் வடிவமைப்புக் குழு மற்றும் அவர்களின் பணிச்சுமை.',
    contractorsPageSubtitle: 'உங்கள் நடப்பு திட்டங்களில் பணிபுரியும் நம்பகமான ஒப்பந்தக்காரர்கள்.',
    categoryLabel: 'வகை',
    supplierLabel: 'சப்ளையர்',
    priceLabel: 'விலை',
    stockLabel: 'இருப்பு',
    inStock: 'இருப்பில் உள்ளது',
    lowStock: 'குறைந்த இருப்பு',
    outOfStock: 'இருப்பு இல்லை',
    specializationLabel: 'நிபுணத்துவம்',
    experienceLabel: 'அனுபவம்',
    activeProjectsLabel: 'செயலில் உள்ள திட்டங்கள்',
    amountLabel: 'தொகை',
    dateLabel: 'தேதி',
    pending: 'நிலுவையில்',
    approved: 'அங்கீகரிக்கப்பட்டது',
    rejected: 'நிராகரிக்கப்பட்டது',
    contractorTypeLabel: 'தொழில் வகை',
    comingSoonTitle: 'விரைவில் வருகிறது',
    comingSoonDesc: 'இந்த பிரிவு உருவாக்கத்தில் உள்ளது, விரைவில் கிடைக்கும்.',
    notFoundTitle: 'பக்கம் கிடைக்கவில்லை',
    notFoundDesc: 'நீங்கள் தேடும் பக்கம் இல்லை அல்லது நகர்த்தப்பட்டுள்ளது.',
    backToDashboard: 'டாஷ்போர்டுக்குத் திரும்பு',
    loginWelcomeTitle: 'மீண்டும் வருக',
    loginSubtitle: 'உங்கள் உள்துறை வடிவமைப்பு திட்டங்களைத் தொடர்ந்து நிர்வகிக்க உள்நுழையவும்.',
    passwordLabel: 'கடவுச்சொல்',
    rememberMe: 'என்னை நினைவில் கொள்',
    forgotPassword: 'கடவுச்சொல் மறந்துவிட்டதா?',
    loginButton: 'உள்நுழை',
    orDivider: 'அல்லது',
    continueWithGoogle: 'Google மூலம் தொடரவும்',
    loginFooter: '© 2026 IDCP போர்ட்டல்',
    invalidCredentials: 'தவறான மின்னஞ்சல் அல்லது கடவுச்சொல்.',
    portalTagline: 'வடிவமை • ஒருங்கிணை • வழங்கு',
    heroTitleLine1: 'இன்டீரியர் டிசைனர்',
    heroTitleLine2: 'ஒருங்கிணைப்பு போர்ட்டல்',
    heroFeature1: 'உள்துறை திட்டங்களை நிர்வகி',
    heroFeature2: 'பொருட்கள் & மேற்கோள்களைக் கண்காணி',
    heroFeature3: 'வடிவமைப்பாளர்கள் & ஒப்பந்தக்காரர்களை ஒருங்கிணை',
    craftingTagline: 'உயர்தர உள்துறை அனுபவங்களை உருவாக்குதல்.',
    logout: 'வெளியேறு',
    demoCredentialsLabel: 'டெமோ சான்றுகள்',
    loginAsLabel: 'இப்படி உள்நுழையவும்',
    roleDesignerLabel: 'வடிவமைப்பாளர்',
    roleContractorLabel: 'ஒப்பந்தக்காரர்'
  },
  hi: {
    dashboard: 'डैशबोर्ड',
    customers: 'ग्राहक',
    designers: 'डिज़ाइनर',
    contractors: 'ठेकेदार',
    suppliers: 'आपूर्तिकर्ता',
    projects: 'परियोजनाएं',
    materials: 'सामग्री',
    appointments: 'नियुक्तियां',
    quotations: 'कोटेशन',
    payments: 'भुगतान',
    reports: 'रिपोर्ट',
    settings: 'सेटिंग्स',
    addCustomer: 'ग्राहक जोड़ें',
    searchPlaceholder: 'ग्राहक, परियोजनाएं खोजें...',
    searchCustomers: 'नाम या परियोजना से खोजें...',
    customerDirectory: 'ग्राहक निर्देशिका',
    allCustomers: 'सभी ग्राहक',
    active: 'सक्रिय',
    inactive: 'निष्क्रिय',
    newCustomers: 'नए ग्राहक',
    viewDetails: 'विवरण देखें',
    delete: 'हटाएं',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    totalCustomers: 'कुल ग्राहक',
    activeCustomers: 'सक्रिय ग्राहक',
    newThisMonth: 'इस महीने नए',
    completedProjects: 'पूर्ण परियोजनाएं',
    pageTitle: 'ग्राहक',
    pageSubtitle: 'अपने ग्राहकों और उनकी इंटीरियर डिज़ाइन परियोजनाओं को प्रबंधित करें।',
    notifications: 'सूचनाएं',
    messages: 'संदेश',
    administratorRole: 'व्यवस्थापक',
    selectLanguage: 'भाषा चुनें',
    toggleToDark: 'डार्क थीम पर स्विच करें',
    toggleToLight: 'लाइट थीम पर स्विच करें',
    pendingQuotations: 'लंबित कोटेशन',
    customerNameLabel: 'ग्राहक का नाम',
    phoneLabel: 'फ़ोन',
    emailLabel: 'ईमेल',
    locationLabel: 'स्थान',
    projectTypeLabel: 'परियोजना प्रकार',
    assignedDesignerLabel: 'नियुक्त डिज़ाइनर',
    statusLabel: 'स्थिति',
    completed: 'पूर्ण',
    nameRequired: 'ग्राहक का नाम आवश्यक है।',
    emptyState: 'कोई ग्राहक नहीं मिला।',
    clearSearch: 'खोज साफ़ करें',
    resetForm: 'रीसेट करें',
    closeModal: 'बंद करें',
    welcomeBackPrefix: 'वापसी पर स्वागत है',
    dashboardSubtitle: 'आज आपकी इंटीरियर डिज़ाइन परियोजनाओं में क्या हो रहा है, यहाँ देखें।',
    activeProjects: 'सक्रिय परियोजनाएं',
    recentProjects: 'हाल की परियोजनाएं',
    recentCustomers: 'हाल के ग्राहक',
    viewAll: 'सभी देखें',
    projectsPageTitle: 'परियोजनाएं',
    projectsPageSubtitle: 'हर इंटीरियर डिज़ाइन परियोजना को शुरुआत से सौंपने तक ट्रैक करें।',
    allProjects: 'सभी परियोजनाएं',
    ongoing: 'चल रहा है',
    onHold: 'रोक दिया गया',
    customerLabel: 'ग्राहक',
    designerLabel: 'डिज़ाइनर',
    startDateLabel: 'आरंभ तिथि',
    endDateLabel: 'समाप्ति तिथि',
    settingsPageTitle: 'सेटिंग्स',
    settingsPageSubtitle: 'IDCP पोर्टल कैसा दिखे, इसे अनुकूलित करें।',
    appearanceSection: 'रूप-रंग',
    appearanceDesc: 'चुनें कि IDCP पोर्टल आपको कैसा दिखे।',
    fontSizeSection: 'फ़ॉन्ट आकार',
    fontSizeDesc: 'पूरे एप्लिकेशन में टेक्स्ट का आकार समायोजित करें।',
    languageSection: 'भाषा',
    languageDesc: 'अपनी पसंदीदा प्रदर्शन भाषा चुनें।',
    themeSection: 'थीम / पृष्ठभूमि',
    themeDesc: 'लाइट और डार्क पोर्टल थीम के बीच स्विच करें।',
    small: 'छोटा',
    medium: 'मध्यम',
    large: 'बड़ा',
    lightTheme: 'लाइट थीम',
    darkTheme: 'डार्क थीम',
    materialsPageSubtitle: 'हर प्रोजेक्ट के लिए सामग्री स्टॉक, आपूर्तिकर्ता और मूल्य को ट्रैक करें।',
    quotationsPageSubtitle: 'अपने ग्राहकों को भेजे गए कोटेशन की समीक्षा और प्रबंधन करें।',
    designersPageSubtitle: 'आपकी इन-हाउस डिज़ाइन टीम और उनका वर्तमान कार्यभार।',
    contractorsPageSubtitle: 'आपकी चल रही परियोजनाओं में काम करने वाले विश्वसनीय ठेकेदार।',
    categoryLabel: 'श्रेणी',
    supplierLabel: 'आपूर्तिकर्ता',
    priceLabel: 'मूल्य',
    stockLabel: 'स्टॉक',
    inStock: 'स्टॉक में',
    lowStock: 'कम स्टॉक',
    outOfStock: 'स्टॉक समाप्त',
    specializationLabel: 'विशेषज्ञता',
    experienceLabel: 'अनुभव',
    activeProjectsLabel: 'सक्रिय परियोजनाएं',
    amountLabel: 'राशि',
    dateLabel: 'तिथि',
    pending: 'लंबित',
    approved: 'स्वीकृत',
    rejected: 'अस्वीकृत',
    contractorTypeLabel: 'कार्य क्षेत्र',
    comingSoonTitle: 'जल्द आ रहा है',
    comingSoonDesc: 'यह मॉड्यूल अभी विकास में है और जल्द ही उपलब्ध होगा।',
    notFoundTitle: 'पृष्ठ नहीं मिला',
    notFoundDesc: 'आप जिस पृष्ठ की तलाश कर रहे हैं वह मौजूद नहीं है या स्थानांतरित कर दिया गया है।',
    backToDashboard: 'डैशबोर्ड पर वापस जाएं',
    loginWelcomeTitle: 'वापसी पर स्वागत है',
    loginSubtitle: 'अपनी इंटीरियर डिज़ाइन परियोजनाओं का प्रबंधन जारी रखने के लिए साइन इन करें।',
    passwordLabel: 'पासवर्ड',
    rememberMe: 'मुझे याद रखें',
    forgotPassword: 'पासवर्ड भूल गए?',
    loginButton: 'लॉगिन',
    orDivider: 'या',
    continueWithGoogle: 'Google से जारी रखें',
    loginFooter: '© 2026 IDCP पोर्टल',
    invalidCredentials: 'अमान्य ईमेल या पासवर्ड।',
    portalTagline: 'डिज़ाइन • समन्वय • वितरण',
    heroTitleLine1: 'इंटीरियर डिज़ाइनर',
    heroTitleLine2: 'समन्वय पोर्टल',
    heroFeature1: 'इंटीरियर परियोजनाओं का प्रबंधन करें',
    heroFeature2: 'सामग्री और कोटेशन ट्रैक करें',
    heroFeature3: 'डिज़ाइनरों और ठेकेदारों का समन्वय करें',
    craftingTagline: 'प्रीमियम इंटीरियर अनुभव तैयार करना।',
    logout: 'लॉगआउट',
    demoCredentialsLabel: 'डेमो लॉगिन जानकारी',
    loginAsLabel: 'इस रूप में लॉगिन करें',
    roleDesignerLabel: 'डिज़ाइनर',
    roleContractorLabel: 'ठेकेदार'
  },
  te: {
    dashboard: 'డాష్‌బోర్డ్',
    customers: 'కస్టమర్లు',
    designers: 'డిజైనర్లు',
    contractors: 'కాంట్రాక్టర్లు',
    suppliers: 'సరఫరాదారులు',
    projects: 'ప్రాజెక్టులు',
    materials: 'సామాగ్రి',
    appointments: 'అపాయింట్‌మెంట్‌లు',
    quotations: 'కోటేషన్లు',
    payments: 'చెల్లింపులు',
    reports: 'నివేదికలు',
    settings: 'సెట్టింగ్‌లు',
    addCustomer: 'కస్టమర్‌ను జోడించండి',
    searchPlaceholder: 'కస్టమర్లు, ప్రాజెక్టులను శోధించండి...',
    searchCustomers: 'పేరు లేదా ప్రాజెక్ట్ ద్వారా శోధించండి...',
    customerDirectory: 'కస్టమర్ డైరెక్టరీ',
    allCustomers: 'అన్ని కస్టమర్లు',
    active: 'యాక్టివ్',
    inactive: 'ఇన్‌యాక్టివ్',
    newCustomers: 'కొత్త కస్టమర్లు',
    viewDetails: 'వివరాలు చూడండి',
    delete: 'తొలగించు',
    save: 'సేవ్ చేయి',
    cancel: 'రద్దు చేయి',
    totalCustomers: 'మొత్తం కస్టమర్లు',
    activeCustomers: 'యాక్టివ్ కస్టమర్లు',
    newThisMonth: 'ఈ నెల కొత్తవి',
    completedProjects: 'పూర్తయిన ప్రాజెక్టులు',
    pageTitle: 'కస్టమర్లు',
    pageSubtitle: 'మీ క్లయింట్లను మరియు వారి ఇంటీరియర్ డిజైన్ ప్రాజెక్టులను నిర్వహించండి.',
    notifications: 'నోటిఫికేషన్లు',
    messages: 'సందేశాలు',
    administratorRole: 'అడ్మినిస్ట్రేటర్',
    selectLanguage: 'భాషను ఎంచుకోండి',
    toggleToDark: 'డార్క్ థీమ్‌కు మారండి',
    toggleToLight: 'లైట్ థీమ్‌కు మారండి',
    pendingQuotations: 'పెండింగ్ కోటేషన్లు',
    customerNameLabel: 'కస్టమర్ పేరు',
    phoneLabel: 'ఫోన్',
    emailLabel: 'ఇమెయిల్',
    locationLabel: 'ప్రాంతం',
    projectTypeLabel: 'ప్రాజెక్ట్ రకం',
    assignedDesignerLabel: 'కేటాయించిన డిజైనర్',
    statusLabel: 'స్థితి',
    completed: 'పూర్తయింది',
    nameRequired: 'కస్టమర్ పేరు అవసరం.',
    emptyState: 'కస్టమర్లు కనుగొనబడలేదు.',
    clearSearch: 'శోధనను క్లియర్ చేయి',
    resetForm: 'రీసెట్ చేయి',
    closeModal: 'మూసివేయి',
    welcomeBackPrefix: 'తిరిగి స్వాగతం',
    dashboardSubtitle: 'ఈరోజు మీ ఇంటీరియర్ డిజైన్ ప్రాజెక్టులలో ఏమి జరుగుతుందో ఇక్కడ చూడండి.',
    activeProjects: 'యాక్టివ్ ప్రాజెక్టులు',
    recentProjects: 'ఇటీవలి ప్రాజెక్టులు',
    recentCustomers: 'ఇటీవలి కస్టమర్లు',
    viewAll: 'అన్నీ చూడండి',
    projectsPageTitle: 'ప్రాజెక్టులు',
    projectsPageSubtitle: 'ప్రతి ఇంటీరియర్ డిజైన్ ప్రాజెక్ట్‌ను ప్రారంభం నుండి అప్పగింత వరకు ట్రాక్ చేయండి.',
    allProjects: 'అన్ని ప్రాజెక్టులు',
    ongoing: 'జరుగుతోంది',
    onHold: 'నిలిపివేయబడింది',
    customerLabel: 'కస్టమర్',
    designerLabel: 'డిజైనర్',
    startDateLabel: 'ప్రారంభ తేదీ',
    endDateLabel: 'ముగింపు తేదీ',
    settingsPageTitle: 'సెట్టింగ్‌లు',
    settingsPageSubtitle: 'IDCP పోర్టల్ మీకు ఎలా కనిపిస్తుందో అనుకూలీకరించండి.',
    appearanceSection: 'రూపం',
    appearanceDesc: 'IDCP పోర్టల్ మీకు ఎలా కనిపించాలో ఎంచుకోండి.',
    fontSizeSection: 'ఫాంట్ పరిమాణం',
    fontSizeDesc: 'మొత్తం అప్లికేషన్‌లో టెక్స్ట్ పరిమాణాన్ని సర్దుబాటు చేయండి.',
    languageSection: 'భాష',
    languageDesc: 'మీకు ఇష్టమైన ప్రదర్శన భాషను ఎంచుకోండి.',
    themeSection: 'థీమ్ / నేపథ్యం',
    themeDesc: 'లైట్ మరియు డార్క్ పోర్టల్ థీమ్‌ల మధ్య మారండి.',
    small: 'చిన్నది',
    medium: 'మధ్యస్థం',
    large: 'పెద్దది',
    lightTheme: 'లైట్ థీమ్',
    darkTheme: 'డార్క్ థీమ్',
    materialsPageSubtitle: 'ప్రతి ప్రాజెక్ట్ కోసం సామాగ్రి నిల్వ, సరఫరాదారులు మరియు ధరలను ట్రాక్ చేయండి.',
    quotationsPageSubtitle: 'మీ కస్టమర్లకు పంపిన కోటేషన్లను సమీక్షించండి మరియు నిర్వహించండి.',
    designersPageSubtitle: 'మీ ఇన్-హౌస్ డిజైన్ బృందం మరియు వారి ప్రస్తుత పని భారం.',
    contractorsPageSubtitle: 'మీ కొనసాగుతున్న ప్రాజెక్టులలో పనిచేస్తున్న విశ్వసనీయ కాంట్రాక్టర్లు.',
    categoryLabel: 'వర్గం',
    supplierLabel: 'సరఫరాదారు',
    priceLabel: 'ధర',
    stockLabel: 'నిల్వ',
    inStock: 'నిల్వలో ఉంది',
    lowStock: 'తక్కువ నిల్వ',
    outOfStock: 'నిల్వ లేదు',
    specializationLabel: 'ప్రత్యేకత',
    experienceLabel: 'అనుభవం',
    activeProjectsLabel: 'యాక్టివ్ ప్రాజెక్టులు',
    amountLabel: 'మొత్తం',
    dateLabel: 'తేదీ',
    pending: 'పెండింగ్‌లో ఉంది',
    approved: 'ఆమోదించబడింది',
    rejected: 'తిరస్కరించబడింది',
    contractorTypeLabel: 'పని విభాగం',
    comingSoonTitle: 'త్వరలో వస్తుంది',
    comingSoonDesc: 'ఈ మాడ్యూల్ అభివృద్ధిలో ఉంది మరియు త్వరలో అందుబాటులోకి వస్తుంది.',
    notFoundTitle: 'పేజీ కనుగొనబడలేదు',
    notFoundDesc: 'మీరు వెతుకుతున్న పేజీ లేదు లేదా తరలించబడింది.',
    backToDashboard: 'డాష్‌బోర్డ్‌కు తిరిగి వెళ్లండి',
    loginWelcomeTitle: 'తిరిగి స్వాగతం',
    loginSubtitle: 'మీ ఇంటీరియర్ డిజైన్ ప్రాజెక్టులను నిర్వహించడం కొనసాగించడానికి సైన్ ఇన్ చేయండి.',
    passwordLabel: 'పాస్‌వర్డ్',
    rememberMe: 'నన్ను గుర్తుంచుకో',
    forgotPassword: 'పాస్‌వర్డ్ మర్చిపోయారా?',
    loginButton: 'లాగిన్',
    orDivider: 'లేదా',
    continueWithGoogle: 'Google తో కొనసాగించండి',
    loginFooter: '© 2026 IDCP పోర్టల్',
    invalidCredentials: 'చెల్లని ఇమెయిల్ లేదా పాస్‌వర్డ్.',
    portalTagline: 'డిజైన్ • సమన్వయం • డెలివరీ',
    heroTitleLine1: 'ఇంటీరియర్ డిజైనర్',
    heroTitleLine2: 'కోఆర్డినేషన్ పోర్టల్',
    heroFeature1: 'ఇంటీరియర్ ప్రాజెక్టులను నిర్వహించండి',
    heroFeature2: 'మెటీరియల్స్ & కోటేషన్లను ట్రాక్ చేయండి',
    heroFeature3: 'డిజైనర్లు & కాంట్రాక్టర్లను సమన్వయం చేయండి',
    craftingTagline: 'ప్రీమియం ఇంటీరియర్ అనుభవాలను రూపొందించడం.',
    logout: 'లాగ్అవుట్',
    demoCredentialsLabel: 'డెమో లాగిన్ వివరాలు',
    loginAsLabel: 'ఇలా లాగిన్ చేయండి',
    roleDesignerLabel: 'డిజైనర్',
    roleContractorLabel: 'కాంట్రాక్టర్'
  },
  ml: {
    dashboard: 'ഡാഷ്ബോർഡ്',
    customers: 'ഉപഭോക്താക്കൾ',
    designers: 'ഡിസൈനർമാർ',
    contractors: 'കോൺട്രാക്ടർമാർ',
    suppliers: 'വിതരണക്കാർ',
    projects: 'പ്രോജക്ടുകൾ',
    materials: 'വസ്തുക്കൾ',
    appointments: 'അപ്പോയിന്റ്മെന്റുകൾ',
    quotations: 'ക്വട്ടേഷനുകൾ',
    payments: 'പേയ്‌മെന്റുകൾ',
    reports: 'റിപ്പോർട്ടുകൾ',
    settings: 'ക്രമീകരണങ്ങൾ',
    addCustomer: 'ഉപഭോക്താവിനെ ചേർക്കുക',
    searchPlaceholder: 'ഉപഭോക്താക്കൾ, പ്രോജക്ടുകൾ തിരയുക...',
    searchCustomers: 'പേര് അല്ലെങ്കിൽ പ്രോജക്റ്റ് പ്രകാരം തിരയുക...',
    customerDirectory: 'ഉപഭോക്തൃ ഡയറക്ടറി',
    allCustomers: 'എല്ലാ ഉപഭോക്താക്കളും',
    active: 'സജീവം',
    inactive: 'നിഷ്ക്രിയം',
    newCustomers: 'പുതിയ ഉപഭോക്താക്കൾ',
    viewDetails: 'വിശദാംശങ്ങൾ കാണുക',
    delete: 'ഇല്ലാതാക്കുക',
    save: 'സേവ് ചെയ്യുക',
    cancel: 'റദ്ദാക്കുക',
    totalCustomers: 'മൊത്തം ഉപഭോക്താക്കൾ',
    activeCustomers: 'സജീവ ഉപഭോക്താക്കൾ',
    newThisMonth: 'ഈ മാസത്തെ പുതിയവ',
    completedProjects: 'പൂർത്തിയായ പ്രോജക്ടുകൾ',
    pageTitle: 'ഉപഭോക്താക്കൾ',
    pageSubtitle: 'നിങ്ങളുടെ ക്ലയന്റുകളെയും അവരുടെ ഇന്റീരിയർ ഡിസൈൻ പ്രോജക്ടുകളെയും കൈകാര്യം ചെയ്യുക.',
    notifications: 'അറിയിപ്പുകൾ',
    messages: 'സന്ദേശങ്ങൾ',
    administratorRole: 'അഡ്മിനിസ്ട്രേറ്റർ',
    selectLanguage: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    toggleToDark: 'ഡാർക്ക് തീമിലേക്ക് മാറുക',
    toggleToLight: 'ലൈറ്റ് തീമിലേക്ക് മാറുക',
    pendingQuotations: 'തീർപ്പാക്കാത്ത ക്വട്ടേഷനുകൾ',
    customerNameLabel: 'ഉപഭോക്താവിന്റെ പേര്',
    phoneLabel: 'ഫോൺ',
    emailLabel: 'ഇമെയിൽ',
    locationLabel: 'സ്ഥലം',
    projectTypeLabel: 'പ്രോജക്ട് തരം',
    assignedDesignerLabel: 'നിയോഗിക്കപ്പെട്ട ഡിസൈനർ',
    statusLabel: 'നില',
    completed: 'പൂർത്തിയായി',
    nameRequired: 'ഉപഭോക്താവിന്റെ പേര് ആവശ്യമാണ്.',
    emptyState: 'ഉപഭോക്താക്കളെ കണ്ടെത്തിയില്ല.',
    clearSearch: 'തിരയൽ മായ്ക്കുക',
    resetForm: 'പുനഃസജ്ജമാക്കുക',
    closeModal: 'അടയ്ക്കുക',
    welcomeBackPrefix: 'തിരികെ സ്വാഗതം',
    dashboardSubtitle: 'ഇന്ന് നിങ്ങളുടെ ഇന്റീരിയർ ഡിസൈൻ പ്രോജക്ടുകളിൽ എന്താണ് സംഭവിക്കുന്നതെന്ന് ഇവിടെ കാണുക.',
    activeProjects: 'സജീവ പ്രോജക്ടുകൾ',
    recentProjects: 'സമീപകാല പ്രോജക്ടുകൾ',
    recentCustomers: 'സമീപകാല ഉപഭോക്താക്കൾ',
    viewAll: 'എല്ലാം കാണുക',
    projectsPageTitle: 'പ്രോജക്ടുകൾ',
    projectsPageSubtitle: 'ഓരോ ഇന്റീരിയർ ഡിസൈൻ പ്രോജക്ടും തുടക്കം മുതൽ കൈമാറ്റം വരെ ട്രാക്ക് ചെയ്യുക.',
    allProjects: 'എല്ലാ പ്രോജക്ടുകളും',
    ongoing: 'നടന്നുകൊണ്ടിരിക്കുന്നു',
    onHold: 'നിർത്തിവച്ചു',
    customerLabel: 'ഉപഭോക്താവ്',
    designerLabel: 'ഡിസൈനർ',
    startDateLabel: 'ആരംഭ തീയതി',
    endDateLabel: 'അവസാന തീയതി',
    settingsPageTitle: 'ക്രമീകരണങ്ങൾ',
    settingsPageSubtitle: 'IDCP പോർട്ടൽ എങ്ങനെ കാണപ്പെടണമെന്ന് ഇഷ്ടാനുസൃതമാക്കുക.',
    appearanceSection: 'രൂപഭാവം',
    appearanceDesc: 'IDCP പോർട്ടൽ നിങ്ങൾക്ക് എങ്ങനെ കാണണമെന്ന് തിരഞ്ഞെടുക്കുക.',
    fontSizeSection: 'ഫോണ്ട് വലുപ്പം',
    fontSizeDesc: 'മുഴുവൻ ആപ്ലിക്കേഷനിലും ടെക്സ്റ്റ് വലുപ്പം ക്രമീകരിക്കുക.',
    languageSection: 'ഭാഷ',
    languageDesc: 'നിങ്ങൾക്ക് ഇഷ്ടമുള്ള ഭാഷ തിരഞ്ഞെടുക്കുക.',
    themeSection: 'തീം / പശ്ചാത്തലം',
    themeDesc: 'ലൈറ്റ്, ഡാർക്ക് പോർട്ടൽ തീമുകൾക്കിടയിൽ മാറുക.',
    small: 'ചെറുത്',
    medium: 'ഇടത്തരം',
    large: 'വലുത്',
    lightTheme: 'ലൈറ്റ് തീം',
    darkTheme: 'ഡാർക്ക് തീം',
    materialsPageSubtitle: 'ഓരോ പ്രോജക്ടിനുമുള്ള മെറ്റീരിയൽ സ്റ്റോക്ക്, വിതരണക്കാർ, വില എന്നിവ ട്രാക്ക് ചെയ്യുക.',
    quotationsPageSubtitle: 'നിങ്ങളുടെ ഉപഭോക്താക്കൾക്ക് അയച്ച ക്വട്ടേഷനുകൾ അവലോകനം ചെയ്ത് കൈകാര്യം ചെയ്യുക.',
    designersPageSubtitle: 'നിങ്ങളുടെ ഇൻ-ഹൗസ് ഡിസൈൻ ടീമും അവരുടെ നിലവിലെ ജോലിഭാരവും.',
    contractorsPageSubtitle: 'നിങ്ങളുടെ നടന്നുകൊണ്ടിരിക്കുന്ന പ്രോജക്ടുകളിൽ പ്രവർത്തിക്കുന്ന വിശ്വസ്ത കോൺട്രാക്ടർമാർ.',
    categoryLabel: 'വിഭാഗം',
    supplierLabel: 'വിതരണക്കാരൻ',
    priceLabel: 'വില',
    stockLabel: 'സ്റ്റോക്ക്',
    inStock: 'സ്റ്റോക്കിൽ ഉണ്ട്',
    lowStock: 'കുറഞ്ഞ സ്റ്റോക്ക്',
    outOfStock: 'സ്റ്റോക്ക് ഇല്ല',
    specializationLabel: 'സ്പെഷ്യലൈസേഷൻ',
    experienceLabel: 'പരിചയം',
    activeProjectsLabel: 'സജീവ പ്രോജക്ടുകൾ',
    amountLabel: 'തുക',
    dateLabel: 'തീയതി',
    pending: 'തീർപ്പാക്കാത്തത്',
    approved: 'അംഗീകരിച്ചു',
    rejected: 'നിരസിച്ചു',
    contractorTypeLabel: 'ജോലി വിഭാഗം',
    comingSoonTitle: 'ഉടൻ വരുന്നു',
    comingSoonDesc: 'ഈ മൊഡ്യൂൾ വികസനത്തിലാണ്, ഉടൻ ലഭ്യമാകും.',
    notFoundTitle: 'പേജ് കണ്ടെത്തിയില്ല',
    notFoundDesc: 'നിങ്ങൾ തിരയുന്ന പേജ് നിലവിലില്ല അല്ലെങ്കിൽ നീക്കം ചെയ്തിരിക്കുന്നു.',
    backToDashboard: 'ഡാഷ്ബോർഡിലേക്ക് മടങ്ങുക',
    loginWelcomeTitle: 'തിരികെ സ്വാഗതം',
    loginSubtitle: 'നിങ്ങളുടെ ഇന്റീരിയർ ഡിസൈൻ പ്രോജക്ടുകൾ തുടർന്നും കൈകാര്യം ചെയ്യാൻ സൈൻ ഇൻ ചെയ്യുക.',
    passwordLabel: 'പാസ്‌വേഡ്',
    rememberMe: 'എന്നെ ഓർക്കുക',
    forgotPassword: 'പാസ്‌വേഡ് മറന്നോ?',
    loginButton: 'ലോഗിൻ',
    orDivider: 'അല്ലെങ്കിൽ',
    continueWithGoogle: 'Google ഉപയോഗിച്ച് തുടരുക',
    loginFooter: '© 2026 IDCP പോർട്ടൽ',
    invalidCredentials: 'അസാധുവായ ഇമെയിൽ അല്ലെങ്കിൽ പാസ്‌വേഡ്.',
    portalTagline: 'ഡിസൈൻ • ഏകോപനം • ഡെലിവർ',
    heroTitleLine1: 'ഇന്റീരിയർ ഡിസൈനർ',
    heroTitleLine2: 'കോർഡിനേഷൻ പോർട്ടൽ',
    heroFeature1: 'ഇന്റീരിയർ പ്രോജക്ടുകൾ കൈകാര്യം ചെയ്യുക',
    heroFeature2: 'മെറ്റീരിയലുകളും ക്വട്ടേഷനുകളും ട്രാക്ക് ചെയ്യുക',
    heroFeature3: 'ഡിസൈനർമാരെയും കോൺട്രാക്ടർമാരെയും ഏകോപിപ്പിക്കുക',
    craftingTagline: 'പ്രീമിയം ഇന്റീരിയർ അനുഭവങ്ങൾ സൃഷ്ടിക്കുന്നു.',
    logout: 'ലോഗ്ഔട്ട്',
    demoCredentialsLabel: 'ഡെമോ ലോഗിൻ വിവരങ്ങൾ',
    loginAsLabel: 'ഇങ്ങനെ ലോഗിൻ ചെയ്യുക',
    roleDesignerLabel: 'ഡിസൈനർ',
    roleContractorLabel: 'കോൺട്രാക്ടർ'
  },
  kn: {
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    customers: 'ಗ್ರಾಹಕರು',
    designers: 'ವಿನ್ಯಾಸಕರು',
    contractors: 'ಗುತ್ತಿಗೆದಾರರು',
    suppliers: 'ಪೂರೈಕೆದಾರರು',
    projects: 'ಯೋಜನೆಗಳು',
    materials: 'ಸಾಮಗ್ರಿಗಳು',
    appointments: 'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳು',
    quotations: 'ಉಲ್ಲೇಖಗಳು',
    payments: 'ಪಾವತಿಗಳು',
    reports: 'ವರದಿಗಳು',
    settings: 'ಸಂಯೋಜನೆಗಳು',
    addCustomer: 'ಗ್ರಾಹಕರನ್ನು ಸೇರಿಸಿ',
    searchPlaceholder: 'ಗ್ರಾಹಕರು, ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಿ...',
    searchCustomers: 'ಹೆಸರು ಅಥವಾ ಯೋಜನೆಯಿಂದ ಹುಡುಕಿ...',
    customerDirectory: 'ಗ್ರಾಹಕರ ಡೈರೆಕ್ಟರಿ',
    allCustomers: 'ಎಲ್ಲಾ ಗ್ರಾಹಕರು',
    active: 'ಸಕ್ರಿಯ',
    inactive: 'ನಿಷ್ಕ್ರಿಯ',
    newCustomers: 'ಹೊಸ ಗ್ರಾಹಕರು',
    viewDetails: 'ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    delete: 'ಅಳಿಸಿ',
    save: 'ಉಳಿಸಿ',
    cancel: 'ರದ್ದುಮಾಡಿ',
    totalCustomers: 'ಒಟ್ಟು ಗ್ರಾಹಕರು',
    activeCustomers: 'ಸಕ್ರಿಯ ಗ್ರಾಹಕರು',
    newThisMonth: 'ಈ ತಿಂಗಳ ಹೊಸವು',
    completedProjects: 'ಪೂರ್ಣಗೊಂಡ ಯೋಜನೆಗಳು',
    pageTitle: 'ಗ್ರಾಹಕರು',
    pageSubtitle: 'ನಿಮ್ಮ ಗ್ರಾಹಕರು ಮತ್ತು ಅವರ ಒಳಾಂಗಣ ವಿನ್ಯಾಸ ಯೋಜನೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ.',
    notifications: 'ಅಧಿಸೂಚನೆಗಳು',
    messages: 'ಸಂದೇಶಗಳು',
    administratorRole: 'ನಿರ್ವಾಹಕ',
    selectLanguage: 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
    toggleToDark: 'ಡಾರ್ಕ್ ಥೀಮ್‌ಗೆ ಬದಲಿಸಿ',
    toggleToLight: 'ಲೈಟ್ ಥೀಮ್‌ಗೆ ಬದಲಿಸಿ',
    pendingQuotations: 'ಬಾಕಿ ಉಲ್ಲೇಖಗಳು',
    customerNameLabel: 'ಗ್ರಾಹಕರ ಹೆಸರು',
    phoneLabel: 'ಫೋನ್',
    emailLabel: 'ಇಮೇಲ್',
    locationLabel: 'ಸ್ಥಳ',
    projectTypeLabel: 'ಯೋಜನೆಯ ಪ್ರಕಾರ',
    assignedDesignerLabel: 'ನಿಯೋಜಿತ ವಿನ್ಯಾಸಕ',
    statusLabel: 'ಸ್ಥಿತಿ',
    completed: 'ಪೂರ್ಣಗೊಂಡಿದೆ',
    nameRequired: 'ಗ್ರಾಹಕರ ಹೆಸರು ಅಗತ್ಯವಿದೆ.',
    emptyState: 'ಯಾವುದೇ ಗ್ರಾಹಕರು ಕಂಡುಬಂದಿಲ್ಲ.',
    clearSearch: 'ಹುಡುಕಾಟವನ್ನು ತೆರವುಗೊಳಿಸಿ',
    resetForm: 'ಮರುಹೊಂದಿಸಿ',
    closeModal: 'ಮುಚ್ಚಿ',
    welcomeBackPrefix: 'ಮತ್ತೆ ಸ್ವಾಗತ',
    dashboardSubtitle: 'ಇಂದು ನಿಮ್ಮ ಒಳಾಂಗಣ ವಿನ್ಯಾಸ ಯೋಜನೆಗಳಲ್ಲಿ ಏನಾಗುತ್ತಿದೆ ಎಂಬುದನ್ನು ಇಲ್ಲಿ ನೋಡಿ.',
    activeProjects: 'ಸಕ್ರಿಯ ಯೋಜನೆಗಳು',
    recentProjects: 'ಇತ್ತೀಚಿನ ಯೋಜನೆಗಳು',
    recentCustomers: 'ಇತ್ತೀಚಿನ ಗ್ರಾಹಕರು',
    viewAll: 'ಎಲ್ಲಾ ನೋಡಿ',
    projectsPageTitle: 'ಯೋಜನೆಗಳು',
    projectsPageSubtitle: 'ಪ್ರತಿ ಒಳಾಂಗಣ ವಿನ್ಯಾಸ ಯೋಜನೆಯನ್ನು ಪ್ರಾರಂಭದಿಂದ ಹಸ್ತಾಂತರದವರೆಗೆ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ.',
    allProjects: 'ಎಲ್ಲಾ ಯೋಜನೆಗಳು',
    ongoing: 'ನಡೆಯುತ್ತಿದೆ',
    onHold: 'ತಡೆಹಿಡಿಯಲಾಗಿದೆ',
    customerLabel: 'ಗ್ರಾಹಕ',
    designerLabel: 'ವಿನ್ಯಾಸಕ',
    startDateLabel: 'ಪ್ರಾರಂಭ ದಿನಾಂಕ',
    endDateLabel: 'ಮುಕ್ತಾಯ ದಿನಾಂಕ',
    settingsPageTitle: 'ಸಂಯೋಜನೆಗಳು',
    settingsPageSubtitle: 'IDCP ಪೋರ್ಟಲ್ ಹೇಗೆ ಕಾಣಿಸುತ್ತದೆ ಎಂಬುದನ್ನು ವೈಯಕ್ತೀಕರಿಸಿ.',
    appearanceSection: 'ನೋಟ',
    appearanceDesc: 'IDCP ಪೋರ್ಟಲ್ ನಿಮಗೆ ಹೇಗೆ ಕಾಣಬೇಕು ಎಂಬುದನ್ನು ಆಯ್ಕೆಮಾಡಿ.',
    fontSizeSection: 'ಫಾಂಟ್ ಗಾತ್ರ',
    fontSizeDesc: 'ಇಡೀ ಅಪ್ಲಿಕೇಶನ್‌ನಲ್ಲಿ ಪಠ್ಯದ ಗಾತ್ರವನ್ನು ಹೊಂದಿಸಿ.',
    languageSection: 'ಭಾಷೆ',
    languageDesc: 'ನಿಮ್ಮ ಆದ್ಯತೆಯ ಪ್ರದರ್ಶನ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ.',
    themeSection: 'ಥೀಮ್ / ಹಿನ್ನೆಲೆ',
    themeDesc: 'ಲೈಟ್ ಮತ್ತು ಡಾರ್ಕ್ ಪೋರ್ಟಲ್ ಥೀಮ್‌ಗಳ ನಡುವೆ ಬದಲಿಸಿ.',
    small: 'ಚಿಕ್ಕದು',
    medium: 'ಮಧ್ಯಮ',
    large: 'ದೊಡ್ಡದು',
    lightTheme: 'ಲೈಟ್ ಥೀಮ್',
    darkTheme: 'ಡಾರ್ಕ್ ಥೀಮ್',
    materialsPageSubtitle: 'ಪ್ರತಿ ಯೋಜನೆಗೆ ಸಾಮಗ್ರಿಗಳ ದಾಸ್ತಾನು, ಪೂರೈಕೆದಾರರು ಮತ್ತು ಬೆಲೆಯನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ.',
    quotationsPageSubtitle: 'ನಿಮ್ಮ ಗ್ರಾಹಕರಿಗೆ ಕಳುಹಿಸಿದ ಉಲ್ಲೇಖಗಳನ್ನು ಪರಿಶೀಲಿಸಿ ಮತ್ತು ನಿರ್ವಹಿಸಿ.',
    designersPageSubtitle: 'ನಿಮ್ಮ ಇನ್-ಹೌಸ್ ವಿನ್ಯಾಸ ತಂಡ ಮತ್ತು ಅವರ ಪ್ರಸ್ತುತ ಕೆಲಸದ ಹೊರೆ.',
    contractorsPageSubtitle: 'ನಿಮ್ಮ ನಡೆಯುತ್ತಿರುವ ಯೋಜನೆಗಳಲ್ಲಿ ಕೆಲಸ ಮಾಡುತ್ತಿರುವ ವಿಶ್ವಾಸಾರ್ಹ ಗುತ್ತಿಗೆದಾರರು.',
    categoryLabel: 'ವರ್ಗ',
    supplierLabel: 'ಪೂರೈಕೆದಾರ',
    priceLabel: 'ಬೆಲೆ',
    stockLabel: 'ದಾಸ್ತಾನು',
    inStock: 'ದಾಸ್ತಾನಿನಲ್ಲಿದೆ',
    lowStock: 'ಕಡಿಮೆ ದಾಸ್ತಾನು',
    outOfStock: 'ದಾಸ್ತಾನು ಇಲ್ಲ',
    specializationLabel: 'ವಿಶೇಷತೆ',
    experienceLabel: 'ಅನುಭವ',
    activeProjectsLabel: 'ಸಕ್ರಿಯ ಯೋಜನೆಗಳು',
    amountLabel: 'ಮೊತ್ತ',
    dateLabel: 'ದಿನಾಂಕ',
    pending: 'ಬಾಕಿ ಇದೆ',
    approved: 'ಅನುಮೋದಿಸಲಾಗಿದೆ',
    rejected: 'ತಿರಸ್ಕರಿಸಲಾಗಿದೆ',
    contractorTypeLabel: 'ಕೆಲಸದ ವಿಭಾಗ',
    comingSoonTitle: 'ಶೀಘ್ರದಲ್ಲೇ ಬರುತ್ತಿದೆ',
    comingSoonDesc: 'ಈ ಮಾಡ್ಯೂಲ್ ಅಭಿವೃದ್ಧಿಯಲ್ಲಿದೆ ಮತ್ತು ಶೀಘ್ರದಲ್ಲೇ ಲಭ್ಯವಿರುತ್ತದೆ.',
    notFoundTitle: 'ಪುಟ ಕಂಡುಬಂದಿಲ್ಲ',
    notFoundDesc: 'ನೀವು ಹುಡುಕುತ್ತಿರುವ ಪುಟ ಅಸ್ತಿತ್ವದಲ್ಲಿಲ್ಲ ಅಥವಾ ಸ್ಥಳಾಂತರಿಸಲಾಗಿದೆ.',
    backToDashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹಿಂತಿರುಗಿ',
    loginWelcomeTitle: 'ಮತ್ತೆ ಸ್ವಾಗತ',
    loginSubtitle: 'ನಿಮ್ಮ ಒಳಾಂಗಣ ವಿನ್ಯಾಸ ಯೋಜನೆಗಳನ್ನು ನಿರ್ವಹಿಸುವುದನ್ನು ಮುಂದುವರಿಸಲು ಸೈನ್ ಇನ್ ಮಾಡಿ.',
    passwordLabel: 'ಪಾಸ್‌ವರ್ಡ್',
    rememberMe: 'ನನ್ನನ್ನು ನೆನಪಿಡಿ',
    forgotPassword: 'ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿರಾ?',
    loginButton: 'ಲಾಗಿನ್',
    orDivider: 'ಅಥವಾ',
    continueWithGoogle: 'Google ನೊಂದಿಗೆ ಮುಂದುವರಿಸಿ',
    loginFooter: '© 2026 IDCP ಪೋರ್ಟಲ್',
    invalidCredentials: 'ಅಮಾನ್ಯ ಇಮೇಲ್ ಅಥವಾ ಪಾಸ್‌ವರ್ಡ್.',
    portalTagline: 'ವಿನ್ಯಾಸ • ಸಂಯೋಜನೆ • ವಿತರಣೆ',
    heroTitleLine1: 'ಇಂಟೀರಿಯರ್ ಡಿಸೈನರ್',
    heroTitleLine2: 'ಸಂಯೋಜನಾ ಪೋರ್ಟಲ್',
    heroFeature1: 'ಒಳಾಂಗಣ ಯೋಜನೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
    heroFeature2: 'ಸಾಮಗ್ರಿಗಳು ಮತ್ತು ಉಲ್ಲೇಖಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    heroFeature3: 'ವಿನ್ಯಾಸಕರು ಮತ್ತು ಗುತ್ತಿಗೆದಾರರನ್ನು ಸಂಯೋಜಿಸಿ',
    craftingTagline: 'ಪ್ರೀಮಿಯಂ ಒಳಾಂಗಣ ಅನುಭವಗಳನ್ನು ರೂಪಿಸುವುದು.',
    logout: 'ಲಾಗ್ಔಟ್',
    demoCredentialsLabel: 'ಡೆಮೊ ಲಾಗಿನ್ ವಿವರಗಳು',
    loginAsLabel: 'ಹೀಗೆ ಲಾಗಿನ್ ಮಾಡಿ',
    roleDesignerLabel: 'ಡಿಸೈನರ್',
    roleContractorLabel: 'ಗುತ್ತಿಗೆದಾರ'
  }
}

export const languageLabels = {
  en: 'English',
  ta: 'தமிழ்',
  hi: 'हिन्दी',
  te: 'తెలుగు',
  ml: 'മലയാളം',
  kn: 'ಕನ್ನಡ'
}

export function ThemeProvider({ children }) {
  const [theme, setTheme] = useState('light')
  const [language, setLanguage] = useState('en')
  // useState: tracks the currently selected font-size option ('small' |
  // 'medium' | 'large'), chosen on the Settings page.
  const [fontSize, setFontSize] = useState('medium')

  const toggleTheme = () => {
    setTheme((prev) => (prev === 'light' ? 'dark' : 'light'))
  }

  // Explicit setter (used by the Settings page, which shows both theme
  // options as buttons) alongside the existing header icon toggle.
  const changeTheme = (nextTheme) => {
    setTheme(nextTheme)
  }

  const changeLanguage = (langCode) => {
    setLanguage(langCode)
  }

  const changeFontSize = (size) => {
    setFontSize(size)
  }

  // useEffect: whenever the selected font size changes, push the matching
  // pixel value onto the <html> element as a CSS variable. global.css reads
  // this variable for the root font-size, and every other font-size in the
  // app is defined in rem, so the whole application scales together.
  useEffect(() => {
    const px = fontSizeValues[fontSize] || fontSizeValues.medium
    document.documentElement.style.setProperty('--app-font-size', `${px}px`)
  }, [fontSize])

  const value = {
    theme,
    toggleTheme,
    changeTheme,
    language,
    changeLanguage,
    fontSize,
    changeFontSize,
    t: translations[language]
  }

  return (
    <ThemeContext.Provider value={value}>
      <div className={theme === 'dark' ? 'app-root dark-theme' : 'app-root light-theme'}>
        {children}
      </div>
    </ThemeContext.Provider>
  )
}
